spring.application.name=booking-service
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/booking_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


# Retry configuration
resilience4j.retry.instances.eventService.max-attempts=3
resilience4j.retry.instances.eventService.wait-duration=1s

# Retry only when Event Service is unavailable.
resilience4j.retry.instances.eventService.retry-exceptions=com.eventhub.bookingservice.exception.EventServiceUnavailableException


# Circuit Breaker configuration
resilience4j.circuitbreaker.instances.eventService.sliding-window-size=5
resilience4j.circuitbreaker.instances.eventService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.eventService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.eventService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.eventService.permitted-number-of-calls-in-half-open-state=2

# Only technical Event Service failures affect the circuit breaker.
resilience4j.circuitbreaker.instances.eventService.record-exceptions=com.eventhub.bookingservice.exception.EventServiceUnavailableException


# Expose selected Actuator endpoints
management.endpoints.web.exposure.include=health,metrics

# Show detailed health information
management.endpoint.health.show-details=always

# Enable Circuit Breaker health reporting
management.health.circuitbreakers.enabled=true

# Register the eventService Circuit Breaker with Actuator health
resilience4j.circuitbreaker.instances.eventService.register-health-indicator=true

